export enum CartActionTypes {
  ADD_TO_CART = 'ADD_TO_CART',
  ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE',
  REMOVE_FROM_CART = 'REMOVE_FROM_CART',
  REMOVE_FROM_CART_FAILURE = 'REMOVE_FROM_CART_FAILURE',
  GET_CART_REQUEST = 'GET_CART_REQUEST',
  GET_CART_SUCCESS = 'GET_CART_SUCCESS',
  GET_CART_ERROR = 'GET_CART_ERROR',
}
